FROM digrouz/debian-s6:latest
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG JAVA_VERSION='21'
ARG MONGO_VERSION='8.0.11'
ARG MONGO_ARCH='amd64'
ARG UNIFI_VERSION='9.2.87'

### Environment variables
ENV TERM='xterm' \
    JAVA_VERSION="${JAVA_VERSION}" \
    MONGO_VERSION="${MONGO_VERSION}" \
    MONGO_ARCH="${MONGO_ARCH}" \
    UNIFI_VERSION="${UNIFI_VERSION}"

# Copy config files
COPY root/ /

### Install Application
RUN set -x && \
    apt-get update && \
    apt-get -y --no-install-recommends install \
      ca-certificates \
      curl \
      binutils \
      gnupg2 \
      openjdk-${JAVA_VERSION}-jre-headless \
      jsvc \
      libcap2 \
      logrotate \
    && \
    MONGO_MAJOR=$(echo "${MONGO_VERSION}" | awk -F '.' '{print $1"."$2}')  && \
    curl -SsL https://repo.mongodb.org/apt/debian/dists/bookworm/mongodb-org/${MONGO_MAJOR}/main/binary-${MONGO_ARCH}/mongodb-org-server_${MONGO_VERSION}_amd64.deb -o /tmp/mongodb-org-server_${MONGO_VERSION}_${MONGO_ARCH}.deb && \
    dpkg -i /tmp/mongodb-org-server_${MONGO_VERSION}_${MONGO_ARCH}.deb && \
    curl -SsL https://dl.ui.com/unifi/${UNIFI_VERSION}/unifi_sysvinit_all.deb -o /tmp/unifi.deb && \
    dpkg -i /tmp/unifi.deb && \
    mkdir -p /config && \
    apt-get -y autoremove && \
    apt-get -y clean && \
    apt-get -y autoclean && \
    rm -rf /tmp/* \
           /var/lib/apt/lists/*  \
           /var/tmp/*

    
# Expose volumes
VOLUME ["/config"]

# Expose ports
EXPOSE 8080 8443 8843 8880 1900/UDP 3478/UDP 10001/UDP
