FROM digrouz/debian-s6:latest
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG UNIFI_VERSION='8.0.28'
ARG MONGO_VERSION='4.4'
ARG JAVA_VERSION='17'

### Environment variables
ENV TERM='xterm' \
    UNIFI_VERSION="${UNIFI_VERSION}" \
    MONGO_VERSION="${MONGO_VERSION}" \
    JAVA_VERSION="${JAVA_VERSION}"

# Copy config files
COPY root/ /

### Install Application
RUN set -x && \
    apt-get update && \
    apt-get -y --no-install-recommends install \
      ca-certificates \
      curl \
      binutils \
      gnupg2 \
      libcurl3-gnutls \
      openjdk-${JAVA_VERSION}-jre-headless \
      jsvc \
      libcap2 \
      logrotate \
    && \
    curl -SsL https://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.1_1.1.1n-0+deb11u5_amd64.deb -o /tmp/libssl1.1_1.1.1n-0+deb11u5_amd64.deb && \
    dpkg -i /tmp/libssl1.1_1.1.1n-0+deb11u5_amd64.deb && \
    curl -SsL https://www.mongodb.org/static/pgp/server-${MONGO_VERSION}.asc -o /tmp/mongo.asc && \
    apt-key add /tmp/mongo.asc && \
    echo "deb http://repo.mongodb.org/apt/debian bookworm/mongodb-org/${MONGO_VERSION} main" | tee /etc/apt/sources.list.d/mongodb-org-${MONGO_VERSION}.list && \
    apt-get update && \
    apt-get -y --no-install-recommends install \
      mongodb-org \
    && \
    curl -SsL https://dl.ui.com/unifi/${UNIFI_VERSION}/unifi_sysvinit_all.deb -o /tmp/unifi.deb && \
    dpkg -i /tmp/unifi.deb && \
    mkdir -p /config && \
    apt-get -y autoremove && \
    apt-get -y clean && \
    apt-get -y autoclean && \
    rm -rf /tmp/* \
           /var/lib/apt/lists/*  \
           /var/tmp/*

    
# Expose volumes
VOLUME ["/config"]

# Expose ports
EXPOSE 8080 8443 8843 8880 1900/UDP 3478/UDP 10001/UDP
