{{- if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "unifi-controller.fullname" . }}-webui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unifi-controller.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.webui.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "unifi-controller.fullname" . }}-webui-svc
                port:
                  name: webui
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.webui.host | quote }}
      secretName: {{ printf "%s-webui-tls" (include "unifi-controller.fullname" .) }}
  {{- end }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "unifi-controller.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName }}
spec:
  entryPoints:
    - {{ .Values.ingress.api.traefik.entrypoint }}
  routes:
  - match: HostSNI(`*`)
    priority: {{ .Values.ingress.api.priority }}
    services:
    - name: {{ include "unifi-controller.fullname" . }}-svc
      port:  8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "unifi-controller.fullname" . }}-webredirect
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName }}
spec:
  entryPoints:
    - {{ .Values.ingress.webredirect.traefik.entrypoint }}
  routes:
  - match: HostSNI(`*`)
    priority: {{ .Values.ingress.webredirect.priority }}
    services:
    - name: {{ include "unifi-controller.fullname" . }}-svc
      port:  8880
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "unifi-controller.fullname" . }}-websecureredirect
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName }}
spec:
  entryPoints:
    - {{ .Values.ingress.websecureredirect.traefik.entrypoint }}
  routes:
  - match: HostSNI(`*`)
    priority: {{ .Values.ingress.websecureredirect.priority }}
    services:
    - name: {{ include "unifi-controller.fullname" . }}-svc
      port:  8843
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ include "unifi-controller.fullname" . }}-l2discovery
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName }}
spec:
  entryPoints:
    - {{ .Values.ingress.l2discovery.traefik.entrypoint }}
  routes:
  - services:
    - name: {{ include "unifi-controller.fullname" . }}-svc
      port:  1900
      weight: {{ .Values.ingress.l2discovery.weight }}
{{- end }}