---
{{- if .Values.persistence.config.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "unifi-controller.fullname" . }}-config-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: unifi-controller 
spec:
  storageClassName: {{ .Values.persistence.config.storageClass }}
  accessModes:
    - {{ .Values.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote }}
{{- end }}
