#!/command/with-contenv sh

if [ ! -d /config/data ];then
  rm -rf /config/data
  mkdir -p /config/data
fi 

if [ ! -d /config/logs ];then
  rm -rf /config/logs
  mkdir -p /config/logs
fi 

if [ ! -d /config/data ];then
  rm -rf /config/run
  mkdir -p /config/run
fi 

if [ -L "/usr/lib/unifi/data" ] && [ "$(readlink /usr/lib/unifi/data)" != "/config/data" ];then
  rm -rf /usr/lib/unifi/data
  ln -s /config/data /usr/lib/unifi/data
fi

if [ -L "/usr/lib/unifi/logs" ] && [ "$(readlink /usr/lib/unifi/logs)" != "/config/logs" ];then
  rm -rf /usr/lib/unifi/logs
  ln -s /config/logs /usr/lib/unifi/logs
fi

if [ -L "/usr/lib/unifi/run" ] && [ "$(readlink /usr/lib/unifi/run)" != "/config/run" ];then
  rm -rf /usr/lib/unifi/run
  ln -s /config/run /usr/lib/unifi/run
fi

if [ ! -e /config/data/system.properties ]; then
    cp /etc/s6-overlay/s6-rc.d/unifi-controller-config/defaults/system.properties /config/data/
fi

if [ -n "$XMX" ]; then
  sed -i "s/unifi.xmx=.*/unifi.xmx=$XMX/" /config/data/system.properties 
fi

if [ -n "$XMS" ]; then
  sed -i "s/unifi.xms=.*/unifi.xms=$XMS/" /config/data/system.properties 
fi

if [ ! -f /config/data/keystore ];then
  keytool -genkey -keyalg RSA -alias unifi -keystore /config/data/keystore \
    -storepass aircontrolenterprise -keypass aircontrolenterprise -validity 3650 \
    -keysize 4096 -dname "cn=unifi" -ext san=dns:unifi
fi