#!/command/with-contenv sh

cd /usr/lib/unifi

exec s6-setuidgid appuser java \
                            -Dfile.encoding=UTF-8 \
                            -Djava.awt.headless=true \
                            -Dapple.awt.UIElement=true \
                            -Dunifi.core.enabled=false \
                            -Xms"${XMS:-256}M" \
                            -Xmx"${XMX:-1024}M" \
                            -Dlog4j2.formatMsgNoLookups=true \
                            -XX:+UseParallelGC \
                            -XX:+ExitOnOutOfMemoryError \
                            -XX:+CrashOnOutOfMemoryError \
                            -XX:ErrorFile=/usr/lib/unifi/logs/hs_err_pid%p.log \
                            -Xlog:gc:logs/gc.log:time:filecount=2,filesize=5M \
                            --add-opens java.base/java.lang=ALL-UNNAMED \
                            --add-opens java.base/java.time=ALL-UNNAMED \
                            --add-opens java.base/sun.security.util=ALL-UNNAMED \
                            --add-opens java.base/java.io=ALL-UNNAMED \
                            --add-opens java.rmi/sun.rmi.transport=ALL-UNNAMED \
                          -jar /usr/lib/unifi/lib/ace.jar start
