name: dockerhub-workflow

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  dockerHubImages:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@main
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push tag latest
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile_debian
          push: true
          tags: ${{ secrets.DOCKERHUB_ORGANISATION }}/unifi-controller:latest
      -
        name: Build and push tag debian
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile_debian
          push: true
          tags: ${{ secrets.DOCKERHUB_ORGANISATION }}/unifi-controller:debian
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ secrets.DOCKERHUB_ORGANISATION }}/unifi-controller
        short-description: ${{ github.event.repository.description }}
